# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: lukka/get-cmake@latest
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build native lib
      run: ./gradlew buildNativeProject
    - name: Build JNI bindings
      run: ./gradlew build
