name: Release

on:
  push:
    tags:
      - '*'

jobs:

  linux:
    name: Build and publish Linux native binaries
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build native lib
        run: ./gradlew buildNativeProject
      - name: Build JNI bindings
        run: ./gradlew build
      - name: Copy Linux native-libs to Azure
        run: azcopy cp "${{ github.workspace }}/physx-jni-natives-linux/src/main/resources" "https://kool.blob.core.windows.net/physx-jni-release/physx-jni-natives-linux/src/main?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true
      - name: Copy Linux CUDA native-libs to Azure
        run: azcopy cp "${{ github.workspace }}/physx-jni-natives-linux-cuda/src/main/resources" "https://kool.blob.core.windows.net/physx-jni-release/physx-jni-natives-linux-cuda/src/main?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: >-
            ${{ github.workspace }}/physx-jni/build/libs/*.jar,
            ${{ github.workspace }}/physx-jni-natives-linux/build/libs/physx-jni-natives-linux-?.?.?.jar,
            ${{ github.workspace }}/physx-jni-natives-linux-cuda/build/libs/physx-jni-natives-linux-cuda-?.?.?.jar
          draft: true
          updateOnlyUnreleased: true

  windows:
    name: Build and publish Windows native binaries
    runs-on: windows-latest
    environment: publish
    permissions:
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build native lib
        run: ./gradlew buildNativeProject
      - name: Build JNI bindings
        run: ./gradlew build
      - name: Copy Windows native-libs to Azure
        run: azcopy cp "${{ github.workspace }}/physx-jni-natives-windows/src/main/resources" "https://kool.blob.core.windows.net/physx-jni-release/physx-jni-natives-windows/src/main?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true
      - name: Copy Windows CUDA native-libs to Azure
        run: azcopy cp "${{ github.workspace }}/physx-jni-natives-windows-cuda/src/main/resources" "https://kool.blob.core.windows.net/physx-jni-release/physx-jni-natives-windows-cuda/src/main?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: >-
            ${{ github.workspace }}/physx-jni-natives-windows/build/libs/physx-jni-natives-windows-?.?.?.jar,
            ${{ github.workspace }}/physx-jni-natives-windows-cuda/build/libs/physx-jni-natives-windows-cuda-?.?.?.jar
          draft: true
          updateOnlyUnreleased: true

  macos:
    name: Build and publish MacOS native binaries
    runs-on: macos-latest
    environment: publish
    permissions:
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install coreutils
        run: brew install coreutils
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build native lib
        run: ./gradlew buildNativeProject
        env:
          PM_PYTHON_EXT: python3
      - name: Build JNI bindings
        run: ./gradlew build
      - name: Copy MacOS native-libs to Azure
        run: azcopy cp "${{ github.workspace }}/physx-jni-natives-macos/src/main/resources" "https://kool.blob.core.windows.net/physx-jni-release/physx-jni-natives-macos/src/main?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true
      - name: Copy MacOS ARM64 native-libs to Azure
        run: azcopy cp "${{ github.workspace }}/physx-jni-natives-macos-arm64/src/main/resources" "https://kool.blob.core.windows.net/physx-jni-release/physx-jni-natives-macos-arm64/src/main?${{ secrets.AZURE_SAS_TOKEN }}" --recursive=true
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: >-
            ${{ github.workspace }}/physx-jni-natives-macos/build/libs/physx-jni-natives-macos-?.?.?.jar,
            ${{ github.workspace }}/physx-jni-natives-macos-arm64/build/libs/physx-jni-natives-macos-arm64-?.?.?.jar
          draft: true
          updateOnlyUnreleased: true